version: '3'
services:
  landing-page:
    image: nginx:alpine
    container_name: soursop_landing
    ports:
      - "8081:80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
